sudo: required
services:
  - docker

before_install:
  - docker build -t belcherman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true belcherman/react-test npm test 

after_success:
  - docker build -t belcherman/multi-client ./client
  - docker build -t belcherman/multi-nginx ./nginx
  - docker build -t belcherman/multi-server ./server
  - docker build -t belcherman/multi-worker ./worker

#log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u belcherman --password-stdin

#push images to docker
  - docker push belcherman/multi-client
  - docker push belcherman/multi-nginx
  - docker push belcherman/multi-server 
  - docker push belcherman/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-242584550674'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  edge: true

