sudo: required
services:
  - docker

before_install:
  - docker build -t belcherman2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true belcherman2/react-test npm test 

after_success:
  - docker build -t belcherman2/multi-client ./client
  - docker build -t belcherman2/multi-nginx ./nginx
  - docker build -t belcherman2/multi-server ./server
  - docker build -t belcherman2/multi-worker ./worker

